### ISSUE TITLE
Logo Enterprise 3 stok alanları hk

### ISSUE THREAD

**Issue by sedatcelik** [ugurozpinar/Logo#1]
Üstad merhaba,
Bir sorum olacaktı. 
Logoda Location tablosundaki stok alanlarını ben birleştirmek istiyorum.
Ancak izin vermiyor
Örnegin 
A30 alanını A250 stok alanı ile
A31 alanını A250 
A31 Alanını A250 alanı ile 

ancak bu location tablosu view oalrak başka bir tablo ile ilintili. (Stoklar tablosu ile)

Özet ile : Bütün stoklarımı A250 toplamak istiyorum.

**Comment by ugurozpinar** [comment]
Sedat Bey örnek bir sql varsa onun üzerinden konuşalım. Location tablosunu ve bağlantılarını bilmiyorum biz kullanmadığımız için ama sql varsa denerim

**Comment by sedatcelik** [comment]
Üstad merhaba

1-Bu location tablosunun tutulduğu yer , bizim stok/ raf  alanlarımız
select * from LG_200_LOCATION

2-Bu tabloda paletlerimizi takip ettiğimiz tablo

SELECT * FROM INF_PALET_STOK_MIKTAR_200

[cid:image001.png@01D656B4.DFA93A40]

İki tablo arasından ilişki var, (Raf) üzerinden

Ben ; 1. Tablodaki alanları ve içindeki paletleri aşağıdaki komut ile update ettim.

update LG_200_LOCATION set CODE='A251' where CODE='A31'

ama yapmak istediğim ;

A30, A31,A32 alanlarını A250 altında toplamak

Bilmem açıklayabildim mi?


Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Uğur Özpınar<mailto:notifications@github.com>
Gönderilme: 10 Temmuz 2020 Cuma 11:06
Kime: ugurozpinar/Logo<mailto:Logo@noreply.github.com>
Bilgi: sedatcelik<mailto:sedatcelik23@hotmail.com>; Author<mailto:author@noreply.github.com>
Konu: Re: [ugurozpinar/Logo] Logo Enterprise 3 stok alanları hk (#1)


Sedat Bey örnek bir sql varsa onun üzerinden konuşalım. Location tablosunu ve bağlantılarını bilmiyorum biz kullanmadığımız için ama sql varsa denerim

**Comment by ugurozpinar** [comment]
INF_PALET_STOK_MIKTAR_200 bir view sanırım. Onun kodunu paylaşır mısın
