### ISSUE TITLE
Logo go3'de fatura oluşturmak.

### ISSUE THREAD

**Issue by hasanakcakoca** [ugurozpinar/Logo#2]
Merhaba Uğur bey,
logo go3'de fatura oluşturmak için sql kodu gerekli,  bu konuda yardımcı olabilir misiniz?

**Comment by Recete** [comment]
Uğur Bey,
Telegram adresinizi yazar mısınız?

**Comment by ugurozpinar** [comment]
uozpinar

> Uğur Bey, Telegram adresinizi yazar mısınız?
