### ISSUE TITLE
Satış Siparişi ve Fatura Bağlantısı

### ISSUE THREAD

**Issue by atakankan** [ugurozpinar/Logo#5]
Merhaba. Satış Siparişi oluşturuyorum. Tablolarda ilgili satırı bulabiliyorum.
O siparişten Fatura kestiriyorum. Onu da tablolarda bulabiliyorum. 

Ama o faturanın o siparişten üretildiğini kaydeden tabloyu bulamıyorum. Nerede yazıyordur?

**Comment by komou** [comment]
Merhaba,
Sipariş-Fatura-İrsaliye arası bağlantıları satırlar üzerinden yapılmaktadır. STLINE tablosu üzerinden bağlantı yapabilirsiniz.
Sorgunuzu yazarsanız vakit bulduğumda yardımcı olabilirim.

**Comment by atakankan** [comment]
Sorgu yok aslında. RestAPI üzerinden satış siparişi oluşturuyorum. Muhasebe eğer faturalandırdıysa, fatura numarasına ve bilgilerine erişmek istiyorum. Satış siparişine sağ tık yapıp "bağlantıyı göster" deyince ilgili fatura görülüyor. API üzerinden o faturaya ulaşmaya çalışıyorum.

**Comment by komou** [comment]
Sipariş satırlarında INVOICEREF olacak oradan bağlantı kurabileceğinizi düşünüyorum sipariş için ORDFICHEREF'e değer vererek
RestApi tarafında çalışmadı xml üzerinden değerlendirmek gerekiyor herhalde. Sorgu olsaydı hızlıca çözerdik.

**Comment by atakankan** [comment]
Mecbur API üzerinden query gönderip, sipariş ID sinden fatura ID sine ulaşıyorum. Sonra başka bir istek ile fatura bilgilerine erişiyorum. Yapacak bişey yok :)

Çok teşekkürler bu arada. Siz söylemeseydiniz mümkün değil aklıma gelmezdi STLINE tablosu
